### ISSUE TITLE
Credential library support for legacy auth config keys

### ISSUE THREAD

**Issue by AaronFriel** [oras-project/oras-credentials-go#1]
Regarding the initiative to create a general authentication library for registries (thanks to @shizhMSFT in #413), I encountered some legacy behavior in the Docker credential helper libraries and thought it should be documented to ensure ORAS supports it in this new library.

Credential helpers may return keys either of the form, e.g., `https://ghcr.io` or `ghcr.io`, or the original Docker index server URL `https://index.docker.io/v1/`. See, Docker issue: https://github.com/docker/docker-credential-helpers/issues/256

To handle this, libraries implementing auth and intending to choose an auth configuration must:

1. Use a `ToHostname` routine to homogenize the input server name, removing the scheme and then path parts after the hostname. This function would take a name like `https://ghcr.io/aaronfriel` and return `ghcr.io`.

2. First attempt a direct lookup in the map (`authConfigs["ghcr.io"]`), and early return on success. Otherwise, iterate over the map and perform the `ToHostname` conversion on each of the keys, returning the first key that equals the input (`"ghcr.io" == ToHostname(key)`).

Example: https://github.com/docker/cli/blob/v20.10.23/cli/config/credentials/file_store.go#L33-L47

**Comment by Wwwsylvia** [comment]
Hi @AaronFriel, thanks for the information! Does this issue occur on both native store (desktop, pass, etc.) and config file store?

**Comment by wangxiaoxuan273** [comment]
> I think so @Wwwsylvia, but this is primarily an advisory issue that we'll need to handle entries with and without `https://` prefixes. On macOS, it looks like the credential store preferentially returns the `https://` prefix as of Feb 6, 2023.

I tested on my mac today, it still prefixes `https://`.
<img width="514" alt="Screenshot 2023-04-16 at 13 42 36" src="https://user-images.githubusercontent.com/103478229/232273781-a831dd65-e12d-4b06-b922-8fd6adfcf7a5.png">

**Comment by Wwwsylvia** [comment]
> I have tested with `oras-credential-go`, we don't need the `https` prefix to retrieve the credentials from OSX keychain. The current implementation of `oras-credential-go` works fine.
> 
> ![Screenshot 2023-04-17 at 12 01 10](https://user-images.githubusercontent.com/103478229/233294608-9b1f3f6d-7c90-4de0-8f54-fd150634bccd.png)

Thanks @wangxiaoxuan273 for the testing!
It looks like adding `https` prefix is a osxkeychain-specific behaviour, and it has been handled by the [`docker-credential-helpers`](https://pkg.go.dev/github.com/docker/docker-credential-helpers) library so that we don't need to worry about that at the `oras-credentials-go` level.
For the `https://index.docker.io/v1/` redirection, we support it in the `Credential()` function (See PR #45).

**Comment by shizhMSFT** [comment]
Closing this issue as it is handled by the osxkeychain helper as mentioned by @wangxiaoxuan273 and @Wwwsylvia.

**Comment by Wwwsylvia** [comment]
The issue still exists.

**Comment by Wwwsylvia** [comment]
Closing as #100 has been merged.
