### ISSUE TITLE
Vote for the release of `v0.4.0`

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-credentials-go#106]
At least 2 approvals are needed from the 3 owners for tagging 51dbb8a529c0a6986075d4194bb9583198681b1d as `v0.4.0`.

- [x]  Shiwei Zhang (@shizhMSFT)
- [x]  Sylvia Lei (@Wwwsylvia)
- [x]  Terry Howe (@TerryHowe)

All previously existing APIs have been moved to [`oras.land/oras-go/v2/registry/remote/credentials`](https://pkg.go.dev/oras.land/oras-go/v2@v2.4.0/registry/remote/credentials). With this release, these APIs will be marked as deprecated and will no longer be maintained in this repository.

See [the change log](https://github.com/oras-project/oras-credentials-go/compare/v0.3.0...51dbb8a529c0a6986075d4194bb9583198681b1d) for more details.
**Please respond LGTM or REJECT (with reasoning).**

**Comment by shizhMSFT** [comment]
LGTM

**Comment by TerryHowe** [comment]
LGTM

**Comment by Wwwsylvia** [comment]
Closing as [`v0.4.0`](https://github.com/oras-project/oras-credentials-go/releases/tag/v0.4.0) has been released.
