### ISSUE TITLE
Vote for archiving `oras-credentials-go`

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-credentials-go#108]
With the release of [`v0.4.0`](https://github.com/oras-project/oras-credentials-go/releases/tag/v0.4.0), all existing APIs have been moved to [oras-go](https://pkg.go.dev/oras.land/oras-go/v2/registry/remote/credentials@v2.4.0) and are now deprecated in `oras-credentials-go`. 
The `oras-credentials-go` repository can now be archived to reduce maintenance costs.

To archive the `oras-credentials-go` repository, at least 2 approvals from from the 3 repository maintainers, or at least 3 approvals from the 4 org-level maintainers are required.

Repository maintainers:
- [x] Shiwei Zhang (@shizhMSFT)
- [x]  Sylvia Lei (@Wwwsylvia)
- [x]  Terry Howe (@TerryHowe)

Org-level maintainers:
- [ ] Andrew Block (@sabre1041)
- [x] Sajay Antony (@sajayantony)
- [x] Shiwei Zhang (@shizhMSFT)
- [x] Steve Lasker (@stevelasker)

**Please respond LGTM or REJECT (with reasoning).**

**Comment by TerryHowe** [comment]
LGTM

**Comment by SteveLasker** [comment]
LGM
