### ISSUE TITLE
Design requirements

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-credentials-go#2]
The design goal of this library is to replace / upgrade the following credential modules
- `oras`: https://github.com/oras-project/oras/tree/main/internal/credential
- `oras-go` v1: https://github.com/oras-project/oras-go/tree/v1/pkg/auth/docker
- `notation`: https://github.com/notaryproject/notation/tree/main/pkg/auth

Related discussions and issues:
- https://github.com/oras-project/oras-go/discussions/413
- https://github.com/oras-project/oras-credentials-go/issues/1
- https://github.com/oras-project/community/issues/24

**Comment by Wwwsylvia** [comment]
Posted a design doc in discussion: #18

**Comment by Wwwsylvia** [comment]
@shizhMSFT Are we good to close this?

**Comment by shizhMSFT** [comment]
> @shizhMSFT Are we good to close this?

Yes, closing as v0.1.0 has been released.
