### ISSUE TITLE
Create examples

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-credentials-go#49]
Examples are needed for:

- [ ] `NewNativeStore`
- [ ] `NewFileStore`
- [ ] `NewStore`
- [ ] `NewStoreFromDocker`
- [ ]  `NewStoreWithFallbacks`
- [ ] `Login`
- [ ] `Logout`
- [ ] `Credential`

**Comment by wangxiaoxuan273** [comment]
I will create multiple pull requests for this issue.
