### ISSUE TITLE
`storeWithFallbacks` should leverage the native store of the fallback store for saving credentials

### ISSUE THREAD

**Issue by Wwwsylvia** [oras-project/oras-credentials-go#71]
Currently, `storeWithFallbacks` only saves credentials in the primary store.
https://github.com/oras-project/oras-credentials-go/blob/97227b115704e3a102099b92910541e0e1e95cda/store.go#L222-L226

However, this pattern does not work well for the case where:
- The primary store does not have native store available
- The primary store disables putting credentials in plaintext
- The fallback store has a native store available

In such case, ideally `storeWithFallbacks` should save the credentials in the native store of the fallback store.

**Comment by priteshbandi** [comment]
Should we also change behavior for Delete operation ?
 https://github.com/oras-project/oras-credentials-go/blob/97227b115704e3a102099b92910541e0e1e95cda/store.go#L228-L232

**Comment by Wwwsylvia** [comment]
> Should we also change behavior for Delete operation ?
> 
> https://github.com/oras-project/oras-credentials-go/blob/97227b115704e3a102099b92910541e0e1e95cda/store.go#L228-L232

I'm wondering how we should fallback for `Delete` operation🤔
In the current implementation, the credential store won't return any error if we try to delete the credential for a key (server address) that is not present in the store.
Do you think we should try to delete the credentials in every fallback store?
