### ISSUE TITLE
Vote for release of `v0.2.0`

### ISSUE THREAD

**Issue by wangxiaoxuan273** [oras-project/oras-credentials-go#79]
At least 2 approvals are needed from the 3 owners for tagging 26b25ce as `v0.2.0`.
- [x] Shiwei Zhang (@shizhMSFT)
- [ ] Sylvia Lei (@Wwwsylvia)
- [x] Terry Howe (@TerryHowe)

The code changes compared to `v0.1.1` include:
- #68 
- #73 
- #74
- #75
- #76
- #77

See [the change log](https://github.com/oras-project/oras-credentials-go/compare/v0.1.1...26b25ce1e68a7619f706c1277e7ff0a36987b8ca) for more details.

Please respond LGTM or REJECT (with reasoning).

**Comment by shizhMSFT** [comment]
LGTM

**Comment by TerryHowe** [comment]
LGTM

**Comment by shizhMSFT** [comment]
Closing as `v0.2.0` has been released.
