### ISSUE TITLE
Feature Suggestion: Add InMemory Store and k8s CredentialProviderConfig Store

### ISSUE THREAD

**Issue by uanid** [oras-project/oras-credentials-go#89]
Hello all,

The currently supported Stores are OS Native, File Store, and Docker Store.

<img width="230" alt="image" src="https://github.com/oras-project/oras-credentials-go/assets/35264628/17402432-15fa-4d5e-979b-65596e29901e">

While using these in server environments, there have been some aspects that could be improved upon. For better adaptability in server environments, I'd like to suggest adding the following two stores:

# InMemory Store
Description: This store saves data directly in memory.
Advantage: Although its implementation might be relatively straightforward, having it provided directly by the orsa-credentials-go library would be highly convenient for users.

# CredentialProviderConfig Store
Description: Instead of the Docker Credentials Helper, this store utilizes the Credentials Provider CLI used by Kubernetes.
Advantage: With this Store, users can seamlessly use the Config utilized in a K8S environment.

Additional Reference: [Kubelet Credential Provider](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-credential-provider/)

I believe the inclusion of these two stores would enhance usability across various server setups. Please consider this proposal and I appreciate any feedback. Thank you.

**Comment by Wwwsylvia** [comment]
Hi @Uanid , thanks a lot for the suggestions! The maintainers will investigate the feasibility of the proposal and get back to you later.
One concern could be that that we don't want to introduce extra dependencies in the go mod, as this repository will be eventually merged into [`oras-go`](https://github.com/oras-project/oras-go) and we hope to keep the dependencies clean there.

**Comment by Wwwsylvia** [comment]
Also please let us know if you are willing to contribute. Feel free to raise PRs! 😀

**Comment by Uanid** [comment]
> Also please let us know if you are willing to contribute. Feel free to raise PRs! 😀

Oh, I wasn't aware that orsa-credentials-go needs to keep its dependency libraries simple. Implementing the k8s CredentialsProviderConfig might be challenging without extra dependencies. I think I'll have to implement it as a separate credentials collection library. Also, I will try to contribute to the InMemory Store.

**Comment by Wwwsylvia** [comment]
> > Also please let us know if you are willing to contribute. Feel free to raise PRs! 😀
> 
> Oh, I wasn't aware that orsa-credentials-go needs to keep its dependency libraries simple. Implementing the k8s CredentialsProviderConfig might be challenging without extra dependencies. I think I'll have to implement it as a separate credentials collection library. Also, I will try to contribute to the InMemory Store.

@Uanid  Thanks for the contribution! 
I think we can still have a store for k8s Credentials Provider as an experimental feature in this repo if the community agree to [the proposal to maintain this repository for experimental features](https://github.com/oras-project/oras-credentials-go/discussions/93). We can move only the current stable features to `oras-go`.

**Comment by Wwwsylvia** [comment]
Hi @Uanid, the `credentials` package has been merged into [oras-go](https://github.com/oras-project/oras-go) . Would you like to also create a PR there for the `MemoryStore`? After that, the existing functions in this repo will be marked as deprecated.

Besides, are you willing to contribute to the k8s CredentialProviderConfig Store to the ORAS project as an experimental feature? If so, do you have any options regarding how we maintain the experimental features? Please take a look at [this discussion](https://github.com/oras-project/oras-credentials-go/discussions/93) if you can.

**Comment by Wwwsylvia** [comment]
@Uanid In case you miss the last message👀

**Comment by Wwwsylvia** [comment]
> This feature is divided into the interface model (DTO) through which the kubelet and provider plugin communicate part and the plugin management part. However, the management part is not modularized, so I had to import the entire k8s.io/kubernetes to use it. I did think this was not a good approach, so I copied the source code of the plugin management directly.
Even with this reduced dependency, many dependencies still remain. I believe it's not a good experience for users of oras-credentials-go to have a significant impact on the entire project because of a very small library.
I am using ORAS while developing the Kubernetes Controller. Therefore, adding kubernetes-related dependencies is not a problem for me. However, for those who want either specific Kubernetes dependencies or fewer dependencies, I think it would be better to rewrite all the code, including the DTO code.

@Uanid This makes sense. Looks like the k8s credentials integration needs to be done in somewhere else, just like your experimental code.
Thank you very much for your inputs!

**Comment by TerryHowe** [comment]
https://github.com/oras-project/oras-go/pull/602

**Comment by TerryHowe** [comment]
Can this issue be closed?

**Comment by uanid** [comment]
@TerryHowe  Yes.
