### ISSUE TITLE
Deprecating APIs

### ISSUE THREAD

**Issue by shizhMSFT** [oras-project/oras-credentials-go#95]
As discussed in #80 and #93, as well as https://github.com/oras-project/oras-go/pull/589 being merged, it is time to mark all moved APIs deprecated.

**Comment by Wwwsylvia** [comment]
We should also update the README to clarify that:

1. The moved APIs are deprecated. Users should use the packages in `oras-go` instead.
2. This repository will be used for developing credentials-related experimental features. Those features can be moved to `oras-go` if applicable.
