### ISSUE TITLE
Request to add auth workflow to OCI wg-auth

### ISSUE THREAD

**Issue by sajayantony** [oras-project/oras-credentials-go#97]
Tracking issue as a request to maintainers here to add docs to how oras-credentials-go or oras-go does auth similar to - https://github.com/opencontainers/wg-auth/pull/6

**Comment by Wwwsylvia** [comment]
Hi @sajayantony, I've sent a PR to the `wg-auth` repo. Please see https://github.com/opencontainers/wg-auth/pull/7.

**Comment by Wwwsylvia** [comment]
Closing as https://github.com/opencontainers/wg-auth/pull/7 has been merged.
